const niceInsults = [
  "A little too eager, aren't we?",
  "Slow down, cowboy!",
  "You're going to break something!",
  "You're like a dog with a bone!",
  "You're like a dog with two bones!",
  "Are you a robot?",
  "New Yorkers are more patient than you!",
  "Googling 'how to be patient' might help!",
  "Have you heard of the phrase 'patience is a virtue'?",
  "Aw c'mon, give the server a break!",
  "Yo chill!",
  "I'm sorry, Dave. I'm afraid I can't do that.",
  "Uh oh, looks like you're in timeout!",
  "Oh no, you've done it now!",
  "Banned for life!",
  "Bing bong, you're wrong!",
  "Be cool, stay in school!",
  "You're on thin ice, buddy!",
  "Like Einstein said, 'Insanity is doing the same thing over and over again and expecting different results.'",
  "Like Bernie Sanders said, 'I am once again asking you to stop.'",
  "It would be cool if you can stop now.",
  "I have your IP address and I'm not afraid to use it!",
  "FBI OPEN UP! Just kidding, but seriously, stop.",
  "Have you tried turning it off and on again?",
  "You have a lot of time on your hands, huh?",
  "24 hours in a day and you're spending it like this?",
  "Your parents must be proud.",
];

export { niceInsults };
